### ISSUE TITLE
Is this or will this be an official plugin?

### ISSUE THREAD

**Issue by dgskwirut** [grizzthedj/smart_proxy_ipam#49]
How do I install this plugin? Your notes mention to read the foreman manual on installing plugins, and those point to a foreman plugin repo, but I do not see the plugin listed there.

https://yum.theforeman.org/plugins/2.2/el7/x86_64/

Do I need to follow the gem and part of the Local Development instructions? I would wish to avoid such a "patchy" way to install the plugin, will it be published in the foreman repo as an official plugin soon?

**Comment by grizzthedj** [comment]
@dgskwirut Currently this plugin implementation is in an incubating stage. The plan is to merge this functionality into the Foreman Smart Proxy core, so that it is available out of the box(without a plugin). I suspect this work might start to happen in the coming months, or early in 2021.

I terms of installation, you just need to run `gem install smart_proxy_ipam` from the smart proxy app directory(which is usually `/usr/share/foreman-proxy`, and add a `Gemfile.local.rb` file in the `bundler.d` directory, that has the below line in it:

```
gem 'smart_proxy_ipam'
```
You will also need to populate and add the IPAM configs to the Smart Proxy `settings.d` directory(I think this will be `/etc/foreman-proxy/settings.d`). Example IPAM configs can be found in the `settings.d` directory of this repo.

Once all of that is done, in the Foreman UI, you will add External IPAM subnets, and associate them with the above configured Smart Proxy.
